### ISSUE TITLE
[rdkafka] Upgrade to rdkafka 4.0

### ISSUE THREAD

**Issue by TiMESPLiNTER** [php-enqueue/enqueue-dev#960] opened 2019-10-07 06:11 UTC
There's a new major version of the rdkafka lib. This issue is to add support for it.

https://github.com/arnaud-lb/php-rdkafka/releases/tag/4.0.0

- [ ] Handle Producer errors (#749)
- [ ] setDefaultTopicConf() is deprecated (#970)

**Comment by nick-zh** [comment] 2019-10-07 06:55
#959

**Comment by Steveb-p** [comment] 2019-10-07 07:37
Yeah, it will be necessary to handle the long standing issue with polling. See #749.

**Comment by nick-zh** [comment] 2019-10-07 07:50
@Steveb-p perfect, let me know if i can assist in any way

**Comment by Steveb-p** [comment] 2019-10-26 14:52
@nick-zh I'm running out of ideas... :smile: What might be the reason that `RdKafkaProducer` returns `null` on `RdKafkaProducer::newTopic` call? How to debug it?

Apparently unit tests do just fine, but when an integration test is run, it fails. It doesn't seem to be anything new from phprdkafka, since I've switched to older versions and it works the same way :confused:

**Comment by nick-zh** [comment] 2019-10-26 20:42
@Steveb-p let me know how i can reproduce this, from the code it is not immediate apparent what could cause this for you. Maybe you can point me to the integration test (i am assuming it's on the enqueue side)

**Comment by Egari** [comment] 2020-09-14 10:41
Has there been any progress on this?
It seems this issue has gone stale and the PR has been waiting for review since Feb.

**Comment by Steveb-p** [comment] 2020-09-14 10:50
@Egari unfortunately I'm not actively working with Kafka anymore, I'm mostly only following other's work related to extension and offering advice :cry:

Are you upgrading an existing project or looking for a solution that involves Kafka, but not necessarily enqueue library?

**Comment by nickpoulos** [comment] 2020-10-04 21:12
I am looking to consume messages from Kafka 2.5.1 using php-enqueue but I am also hitting a wall due to this error.  

But after reading all these comments I am pretty concerned at this point, is php-enqueue broken as far as latest Kafka support is concerned? Not looking forward to exploring alternate packages but I am in a bit of a jam with time.

**Comment by nick-zh** [comment] 2020-10-05 05:02
@nickpoulos which error are you refering to? Support for `php-rdkafka:4.x` has been merged with #959 and was released with `0.10.4` from what i can see.
As i side note, supporting newer Kafka versions is almost never an issue, you might just not have the latest features available if `php-rdkafka` is e.g. on `v3`

**Comment by nick-zh** [comment] 2020-10-09 17:31
@makasim the issues mentioned have been resolved, so this issue can be closed :v:

**Closed** 2020-10-09 17:39 UTC
Labels: pinned
