### ISSUE TITLE
[redis] LogicException on set priority

### ISSUE THREAD

**Issue by FrankGiesecke** [php-enqueue/enqueue-dev#635] opened 2018-11-15 11:53 UTC
The method `\Enqueue\Redis\RedisProducer::setPriority` currently throws an logic exception for the reason, that this isn't implemented.
This exception happens on consuming data from the queue.

But it is possible to send messages having a priority.

Therefor, the whole queue went invalid. It's no longer possible to process messages if this happens.

If the Redis producer doesn't care about priority, this information should be simply ignored.
Throwing an exception isn't necessary and useful at all.

**Comment by makasim** [comment] 2018-11-15 12:03
What redis transport version are you referring too?

**Comment by makasim** [comment] 2018-11-15 12:05
It should throw [PriorityNotSupportedException](https://github.com/queue-interop/queue-interop/blob/master/src/Exception/PriorityNotSupportedException.php)

**Comment by FrankGiesecke** [comment] 2018-11-15 12:07
I'm referring the version form master. There is an `throw new \LogicException('Not implemented');` in the method.

Will the problem be solved if the method throws an `PriorityNotSupportedException`?

**Comment by FrankGiesecke** [comment] 2018-11-15 12:09
As I can see, there are more producers throwing the LogicException :(

**Comment by makasim** [comment] 2018-11-15 12:22
They should be fixed

**Comment by FrankGiesecke** [comment] 2018-11-15 12:32
I've opened a PR who will fix the exceptions #637

**Comment by FrankGiesecke** [comment] 2018-11-15 12:48
FYI: After fixing the exceptions, I'm getting the feared behavior:

The Consumer prints out
```log
queue_1         | In PriorityNotSupportedException.php line 16:
queue_1         |                                                   
queue_1         |   The provider does not support priority feature
```

This should not be, shouldn't it?

**Comment by makasim** [comment] 2018-11-15 12:49
Could you add `-vvv`. I want to see a stacktrace.

**Comment by FrankGiesecke** [comment] 2018-11-15 12:57
```
In PriorityNotSupportedException.php line 16:
                                                           
  [Interop\Queue\Exception\PriorityNotSupportedException]  
  The provider does not support priority feature           
                                                           

Exception trace:
 Interop\Queue\Exception\PriorityNotSupportedException::providerDoestNotSupportIt() at /var/www/app/vendor/enqueue/redis/RedisProducer.php:98
 Enqueue\Redis\RedisProducer->setPriority() at /var/www/app/vendor/enqueue/enqueue/Client/Driver/GenericDriver.php:113
 Enqueue\Client\Driver\GenericDriver->sendToProcessor() at /var/www/app/vendor/enqueue/enqueue/Client/RouterProcessor.php:57
 Enqueue\Client\RouterProcessor->process() at /var/www/app/vendor/enqueue/enqueue/Client/DelegateProcessor.php:38
 Enqueue\Client\DelegateProcessor->process() at /var/www/app/vendor/enqueue/enqueue/Consumption/QueueConsumer.php:197
 Enqueue\Consumption\QueueConsumer->Enqueue\Consumption\{closure}() at n/a:n/a
 call_user_func() at /var/www/app/vendor/enqueue/redis/RedisSubscriptionConsumer.php:75
 Enqueue\Redis\RedisSubscriptionConsumer->consume() at /var/www/app/vendor/enqueue/enqueue/Consumption/QueueConsumer.php:264
 Enqueue\Consumption\QueueConsumer->consume() at /var/www/app/vendor/enqueue/enqueue/Symfony/Client/ConsumeCommand.php:139
 Enqueue\Symfony\Client\ConsumeCommand->execute() at /var/www/app/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/app/vendor/symfony/console/Application.php:904
 Symfony\Component\Console\Application->doRunCommand() at /var/www/app/vendor/symfony/framework-bundle/Console/Application.php:89
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/app/vendor/symfony/console/Application.php:262
 Symfony\Component\Console\Application->doRun() at /var/www/app/vendor/symfony/framework-bundle/Console/Application.php:75
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/app/vendor/symfony/console/Application.php:145
 Symfony\Component\Console\Application->run() at /var/www/app/bin/console:39
```

**Comment by makasim** [comment] 2018-11-15 13:02
hm, could you post message headers, properties? Have you set priority somewhere yourself?

**Comment by FrankGiesecke** [comment] 2018-11-15 13:30
I have created a message object with a given priority.
```php
$message = new Message();
$message->setPriority(MessagePriority::HIGH);
$message->setBody($body);
```

This was sendet to the queue
```php
$this->producer->sendEvent($topic, $message);
```

After this, the consumer fetches the message and is gone :(

**Comment by makasim** [comment] 2018-11-15 13:34
That's expected behavior, do not set priority if your transport does not support it. In future, we will add ability to [instruct client to ignore these options if not supported](https://github.com/php-enqueue/enqueue-dev/issues/590)

**Closed** 2018-11-15 13:34 UTC

**Comment by FrankGiesecke** [comment] 2018-11-15 13:50
But this makes no sense. The `enqueue` package will give the ability to exchange the queue service by using different transport.

Adopting the code to use the different transports will break this benefit! 😞 

If a transport doesn't support a feature, it should be ignored instead ending up in an error.

**Comment by makasim** [comment] 2018-11-15 13:53
I disagree with you it should let you know that the feature is not supported. The feature could be critical for an application, such as delaying a message for some period of time. 

> In future, we will add ability to instruct client to ignore these options if not supported

That would do what you need, right? Feel free to send a PR.

**Comment by FrankGiesecke** [comment] 2018-11-15 14:02
BTW: what about PR #637

**Comment by makasim** [comment] 2018-11-15 14:03
@FrankGiesecke merged, thank you!

**Comment by Toflar** [comment] 2019-01-08 10:34
Picking up on this issue because it's related: Do you think it would be even possible to introduce efficient priority handling in Redis using maybe `ZINCRBY` and co.?

**Comment by makasim** [comment] 2019-01-08 10:43
@Toflar I am not much into it. You could try.

**Comment by Toflar** [comment] 2019-02-01 17:04
@ASKozienko as you contributed the new Redis implementation, wdyt?

**Comment by makasim** [comment] 2019-02-01 20:45
He is on vacation at the moment and will be back the week after next. Do not expect an answer till than

**Comment by Toflar** [comment] 2019-02-01 20:52
Cool, thanks for the hint! We'll let him enjoy vacation then 🍹  I had a closer look at the current implementation and unfortunately he used sorted set scores already for the "failover" implementation so things are put back to the queue if they never got acknowledged.
However, maybe the approaches could be combined but I don't want to fiddle around with the lua scripts etc. before I get his opinion on it 😄

**Comment by Toflar** [comment] 2019-03-04 21:51
Ping @ASKozienko :)
